// react-jest/src/containers/TodoList/index.js
import React, { Component } from "react";
// import axios from 'axios'
import Header from "./components/Header";
import UndoList from "./components/UndoList";
import "./index.css";

class TodoList extends Component {
  constructor(props) {
    super(props);
    this.state = {
      undoList: [],
    };
  }

  /*
  componentDidMount(){
    axios.get('/undoList.json').then(res => {
      this.setState({
        undoList: res.data
      })
    }).catch(e => {})
  }
  */

  handleAddUndoItem = (value) => {
    this.setState((state) => ({
      undoList: [...state.undoList, { status: "div", value }],
    }));
  };

  handleDeleteUndoItem = (index) => {
    const newUndoList = [...this.state.undoList];
    newUndoList.splice(index, 1);
    this.setState({
      undoList: newUndoList,
    });
  };

  handleChangeItemStatus = (index) => {
    const newUndoList = [...this.state.undoList];
    newUndoList[index].status = "input";
    this.setState({
      undoList: newUndoList,
    });
  };

  handleResetItemStauts = (index) => {
    const newUndoList = [...this.state.undoList];
    newUndoList[index].status = "div";
    this.setState({
      undoList: newUndoList,
    });
  };

  handleChangeItemValue = (obj) => {
    const newUndoList = [...this.state.undoList];
    newUndoList[obj.index].value = obj.value;
    this.setState({
      undoList: newUndoList,
    });
  };

  render() {
    return (
      <div>
        <Header addUndoItem={this.handleAddUndoItem} />
        <UndoList
          valueChange={this.handleChangeItemValue}
          resetStatus={this.handleResetItemStauts}
          changeStatus={this.handleChangeItemStatus}
          deleteItem={this.handleDeleteUndoItem}
          list={this.state.undoList}
        />
      </div>
    );
  }
}

export default TodoList;

// vue-jest/src/containers/TodoList/TodoList.vue
<template>
  <div>
    <Header @add="handleAddUndoItem" />
    <UndoList
      :list="undoList"
      @delete="handleDeleteItem"
      @status="handleChangeStatus"
      @reset="handleResetStatus"
      @change="handleChangeItemValue"
    />
  </div>
</template>

<script>
import axios from 'axios'
import Header from './components/Header'
import UndoList from './components/UndoList'

export default {
  name: 'TodoList',
  components: {
    Header,
    UndoList
  },
  data () {
    return {
      undoList: []
    }
  },
  mounted () {
    axios.get('/getUndoList.json').then(res => {
      this.undoList = res.data
    }).catch(e => {})
  },
  methods: {
    handleAddUndoItem (inputValue) {
      this.undoList.push({
        status: 'div',
        value: inputValue
      })
    },
    handleDeleteItem (index) {
      this.undoList.splice(index, 1)
    },
    handleChangeStatus (index) {
      const newList = []
      this.undoList.forEach((item, itemIndex) => {
        if (itemIndex === index) newList.push({ status: 'input', value: item.value })
        else newList.push({ status: 'div', value: item.value })
      })
      this.undoList = newList
    },
    handleResetStatus () {
      const newList = []
      this.undoList.forEach(item => {
        newList.push({ status: 'div', value: item.value })
      })
      this.undoList = newList
    },
    handleChangeItemValue (obj) {
      this.undoList[obj.index].value = obj.value
    }
  }
}
</script>

<style scoped lang="stylus">

</style>
